Update cpc

diff --git a/bin/cpc b/bin/cpc
--- a/bin/cpc
+++ b/bin/cpc
@@ -72,8 +72,8 @@ function atcoder_url_get_task_id() {
 function atcoder_url_get_task_dir() {
   local url="$1"
   local contest_id task_id
-  contest_id="$(atcoder_url_get_contest_id "$url")"
-  task_id="$(atcoder_url_get_task_id "$url")"
+  contest_id=$(atcoder_url_get_contest_id "$url")
+  task_id=$(atcoder_url_get_task_id "$url")
   echo "$(atcoder_get_root_dir)/$contest_id/$task_id"
 }
 
@@ -85,7 +85,7 @@ function atcoder_task_get_testcase_dir() {
 function atcoder_task_create_new_answer() {
   local task_dir="$1" language="$2"
   local index
-  index="$(find "$task_dir" -maxdepth 1 -type f -name "*.$language" | wc -l | awk '{ print $1 }')"
+  index=$(find "$task_dir" -maxdepth 1 -type f -name "*.$language" | wc -l | awk '{ print $1 }')
   echo "$task_dir/main_$index.$language"
 }
 
@@ -95,106 +95,143 @@ function atcoder_task_select_answer() {
 }
 
 # ////////////////////////////////////////////////////////////////
-# Runner
+# Test Runner
 # ////////////////////////////////////////////////////////////////
 
-function run_cpp() {
-  local src="$1" in="$2" out="$3"
-  local dest="${src%.*}"
+function run_tests() {
+  local answer="$1" testcase_dir="$2"
 
-  [[ ! "$src" =~ ^/.* ]] && echo "src must be abstract path: $src" && exit 1
+  function run() {
+    local command="$1" testcase_dir="$2"
 
-  function build() {
+    function judge() {
+      local command="$1" input="$2" expected="$3"
+
+      function red() { tput setaf 1; }
+      function green() { tput setaf 2; }
+      function blue() { tput setaf 5; }
+      function nc() { tput sgr0; }
+
+      function cols() { tput cols; }
+      function bar() { seq -f "$1" -s "" "$(cols)"; }
+
+      function report_ac() {
+        local result="$1"
+        bar "-"
+        echo "Input:"
+        echo "$(cat "$input")"
+        echo ""
+        echo "Output:"
+        echo "$(cat "$result")"
+        echo ""
+        echo "Status: $(green)AC$(nc)"
+        bar "-"
+      }
+
+      function report_wa() {
+        local result="$1"
+        bar "-"
+        echo "Input:"
+        echo "$(cat "$input")"
+        echo ""
+        echo "Output:"
+        echo "$(cat "$result")"
+        echo ""
+        echo "Status: $(red)WA$(nc)"
+        bar "-"
+      }
+
+      function report_re() {
+        bar "-"
+        echo "Input:"
+        echo "$(cat "$input")"
+        echo ""
+        echo "Status: $(blue)RE$(nc)"
+        bar "-"
+      }
+
+      function report_tle() {
+        bar "-"
+        echo "Input:"
+        echo "$(cat "$input")"
+        echo ""
+        echo "Status: $(blue)TLE$(nc)"
+        echo "2 seconds exceeded."
+        bar "-"
+      }
+
+      function report_summary() {
+        local ok="$1" ng="$2"
+        bar "="
+        echo "$(green)$ok$(nc) passed, $(red)$ng$(nc) failed."
+        bar "="
+      }
+
+      local actual
+      actual=$(mktemp)
+      trap "rm -f $actual" EXIT
+
+      timeout 2 "$command" <"$input" >"$actual"
+      local stat=$?
+      if [ $stat -eq 124 ]; then
+        report_tle && return 1
+      elif [ $stat -ne 0 ]; then
+        report_re && return 1
+      fi
+
+      local result
+      result=$(mktemp)
+      trap "rm -f $result" EXIT
+
+      if ! sdiff "$expected" "$actual" -w "$(cols)" >"$result"; then
+        report_wa "$result" && return 1
+      fi
+
+      report_ac "$result" && return 0
+    }
+
+    input() { echo "$testcase_dir/sample-$1.in"; }
+    expected() { echo "$testcase_dir/sample-$1.out"; }
+
+    local i=1 ok=0 ng=0
+    while [ -f "$(input $i)" ] && [ -f "$(expected $i)" ]; do
+      if judge "$command" "$(input $i)" "$(expected $i)"; then
+        ok=$((ok + 1))
+      else
+        ng=$((ng + 1))
+      fi
+      i=$((i + 1))
+    done
+    report_summary $ok $ng
+  }
+
+  function build_cpp() {
+    local src="$1" dest="$2"
+
     local cxx cxxflags
     cxx="/usr/local/bin/g++-9"
     cxxflags=($(cat "$g_script_dir/../compile_flags.txt"))
 
-    $cxx "$src" -o "$dest" "${cxxflags[*]}"
+    $cxx "$src" -o "$dest" ${cxxflags[*]}
   }
 
-  function run() {
-    $dest <"$in" >"$out"
-  }
+  local extension
+  extension="${answer##*.}"
 
-  function clean() {
-    rm -f "$dest"
-  }
-
-  build && trap clean EXIT && run
-}
-
-build() {
-  local cxx cxxflags src target
-
-  cxx="/usr/local/bin/g++-9"
-  cxxflags=($(cat "$g_script_dir/../compile_flags.txt"))
-  src="$(realpath "$1")"
-  target="${src%.*}"
-
-  $cxx ${cxxflags[*]} "$src" -o "$target"
-
-  echo "$target"
-}
-
-run_tests() {
-  local red='\033[0;31m' green='\033[0;32m' nocolor='\033[0m'
-  local target="$1" testcase_dir="$2"
-
-  cols() { tput cols; }
-
-  str_repeat() { seq -f "$1" -s "" "$2"; }
-
-  bar() { echo "$(str_repeat "$1" "$(cols)")"; }
-
-  assert() {
-    local target="$1" in="$2" out="$3"
-    local actual result_diff result_status message
-
-    actual="$(mktemp)"
-    trap "rm -f $actual" EXIT
-    $target <"$in" >"$actual"
-
-    result_diff="$(sdiff "$out" "$actual" -w "$(cols)")"
-    result_status=$?
-    if [ $result_status -eq 0 ]; then
-      message="${green}OK${nocolor}"
-    else
-      message="${red}NG${nocolor}"
+  case $extension in
+  cpp)
+    local dest="${answer%.*}"
+    trap "rm -f $dest" EXIT
+    if ! build_cpp "$answer" "$dest"; then
+      echo "build failed" && exit 1
     fi
 
-    bar "-"
-    echo Input:
-    echo "$(cat $in)"
-    echo
-    echo Output:
-    echo $result_diff
-    echo
-    echo Status:
-    echo $message
-    bar "-"
-
-    return $result_status
-  }
-
-  in_file() { echo "$testcase_dir/sample-$1.in"; }
-
-  out_file() { echo "$testcase_dir/sample-$1.out"; }
-
-  local i=1 result_status n_ok=0 n_ng=0
-  while [ -f "$(in_file $i)" ] && [ -f "$(out_file $i)" ]; do
-    assert "$target" "$(in_file $i)" "$(out_file $i)"
-    if [ $? -eq 0 ]; then
-      n_ok=$((n_ok + 1))
-    else
-      n_ng=$((n_ng + 1))
+    local command="$dest"
+    if ! run "$command" "$testcase_dir"; then
+      echo "error occurred when running test" && exit 1
     fi
-    i=$((i + 1))
-  done
-
-  bar "="
-  [ $n_ok -gt 0 ] && echo "${green}${n_ok}${nocolor} passed."
-  [ $n_ng -gt 0 ] && echo "${red}${n_ng}${nocolor} failed."
-  bar "="
+    ;;
+  esac
 }
 
 # ////////////////////////////////////////////////////////////////
@@ -206,15 +243,15 @@ function new_command() {
     local url="$1" language="$2"
 
     if ! validate_language "$language"; then
-      language="$(select_language)"
+      language=$(select_language)
     fi
 
     local task_dir template new_answer testcase_dir
 
-    task_dir="$(atcoder_url_get_task_dir "$url")"
-    template="$(atcoder_get_template "$language")"
-    new_answer="$(atcoder_task_create_new_answer "$task_dir" "$language")"
-    testcase_dir="$(atcoder_task_get_testcase_dir "$task_dir")"
+    task_dir=$(atcoder_url_get_task_dir "$url")
+    template=$(atcoder_get_template "$language")
+    new_answer=$(atcoder_task_create_new_answer "$task_dir" "$language")
+    testcase_dir=$(atcoder_task_get_testcase_dir "$task_dir")
 
     mkdir -p "$task_dir" &&
       cp "$template" "$new_answer" &&
@@ -233,28 +270,22 @@ function new_command() {
 function test_command() {
   function test_atcoder() {
     local url="$1"
-    local task_dir answer testcase_dir target
-    task_dir="$(atcoder_url_get_task_dir "$url")"
-    answer="$(atcoder_task_select_answer "$task_dir")"
-    testcase_dir="$(atcoder_task_get_testcase_dir "$task_dir")"
+    local task_dir answer testcase_dir
+    task_dir=$(atcoder_url_get_task_dir "$url")
+    answer=$(atcoder_task_select_answer "$task_dir")
+    testcase_dir=$(atcoder_task_get_testcase_dir "$task_dir")
 
-    target="$(build "$answer")"
-    trap "rm -f $target" EXIT
-
-    run_tests "$target" "$testcase_dir"
+    run_tests "$answer" "$testcase_dir"
   }
 
   function test_local() {
     local task_dir="$1"
-    local answer testcase_dir target
-    task_dir="$(realpath "$task_dir")"
-    answer="$(atcoder_task_select_answer "$task_dir")"
-    testcase_dir="$(atcoder_task_get_testcase_dir "$task_dir")"
+    local answer testcase_dir
+    task_dir=$(realpath "$task_dir")
+    answer=$(atcoder_task_select_answer "$task_dir")
+    testcase_dir=$(atcoder_task_get_testcase_dir "$task_dir")
 
-    target="$(build "$answer")"
-    trap "rm -f $target" EXIT
-
-    run_tests "$target" "$testcase_dir"
+    run_tests "$answer" "$testcase_dir"
   }
 
   [ $# -lt 1 ] && echo "too few arguments" && exit 1
@@ -272,8 +303,8 @@ function submit_command() {
   function submit_atcoder() {
     local url="$1"
     local task_dir answer
-    task_dir="$(atcoder_url_get_task_dir "$url")"
-    answer="$(atcoder_task_select_answer "$task_dir")"
+    task_dir=$(atcoder_url_get_task_dir "$url")
+    answer=$(atcoder_task_select_answer "$task_dir")
 
     oj s "$url" "$answer" -y
   }
